name: Basic CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest matplotlib seaborn pandas
        
    - name: Install package locally
      run: |
        pip install .
        
    - name: Run tests
      run: |
        pytest tests/ -v
        
    - name: Test main examples
      run: |
        cd examples
        export MPLBACKEND=Agg
        echo "Testing minimal_benchmark.py..."
        python minimal_benchmark.py
        echo "Testing example_synthetic.py..."
        python example_synthetic.py